/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teris.cx;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Mactavish
 */
public class GamePanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePanel
     */
    public int x;
    public int y;
    int block1[];   //gp里的物块
    int blockIndex;  //对应在Blocks里的一级索引，0-6里的一个数
    Color c;        //方便给物块换颜色
    int[][] fix;    //固定的灰色物块
    boolean isGameover = false;     

    public GamePanel() {
        initComponents();

        blockIndex = 0;
        x = 40;
        y = -20;
        fix = new int[22][10];
    }

    public void drawBlocks(Graphics g, int[] block) {

        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                if (block[i * 4 + j] == 1) {
                    g.fill3DRect(x + j * 20, y + i * 20, 20, 20, true);
                }
            }
        }
        g.setColor(Color.gray);
        for (int i = 0; i < 20; i++) {
            for (int j = 0; j < 10; j++) {
                if (fix[i][j] == 1) {
                    g.fill3DRect(20 * j, 380 - 20 * i, 20, 20, true);

                }
            }
        }
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        //setBorder(g,bl.t1);

        if (isGameover) {
            g.drawString("游戏结束！", 40, 200);
        } else {
            g.setColor(c);
            drawBlocks(g, block1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
