/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teris.cx;

import java.awt.Graphics;
import java.util.Random;

/**
 *
 *
 *
 * @author Mactavish
 */
public class GameFrame extends javax.swing.JFrame {

    Controller ctrl;
    GamePanel gp;
    Graphics g;
    BlockPanel bp;
    ScorePanel sp;

    /**
     * Creates new form NewJFrame
     */
    public GameFrame() {
        initComponents();
        //这三行放音乐
        
        //String filepath = "D:\\PutJavacodehere\\Teris\\src\\teris\\cx\\bgm.wav";
        String filepath = "bgm.wav";
        MusicStuff musicObject = new MusicStuff();
        musicObject.playMusic(filepath);

        gp = new GamePanel();
        bp = new BlockPanel();
        sp = new ScorePanel();
        ctrl = new Controller(gp, bp, sp);

        this.getContentPane().add(bp);
        this.getContentPane().add(sp);
        this.getContentPane().add(gp);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaption);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel1.setText("下一个图形");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel2.setText("游戏状态");

        jButton1.setText("暂停游戏/返回游戏");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("开始游戏");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("降低速度");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("增加速度");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel3.setText("自制俄罗斯方块");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel4.setText("通信1801 陈旭");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel3)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //这个按键控制暂停，恢复游戏
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (ctrl.pause) {
            ctrl.pause = false;
            ctrl.resume();
        } else {
            ctrl.pause = true;
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    //这个按键控制暂停，开始or重启游戏
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (ctrl.restart) {     //如果重启就先关线程，重设参数
            ctrl.shutThread = true;
            ctrl.temp.interrupt();
            ctrl.resetParameters();
        } else {
            ctrl.restart = true;
        }
        gp.setSize(200, 400);
        gp.setLocation(50, 50);
        bp.setSize(100, 80);
        bp.setLocation(290, 50);
        sp.setSize(80, 60);
        sp.setLocation(290, 160);

        Blocks block = new Blocks();
        Random random = new Random();           //设置首先出现的gp和bp里的物块
        ctrl.rand = random.nextInt(7);
        this.gp.block1 = block.graph[ctrl.rand][0];
        bp.repaint();
        this.bp.rand = random.nextInt(7);
        this.bp.block = block.graph[bp.rand][0];

        ctrl.resetColor();
        ctrl.shutThread = false;
        ctrl.runRepeatableThread();
    }//GEN-LAST:event_jButton2ActionPerformed

    //这个按键控制游戏速度，只能加速
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (sp.gameSpeed < 6) {
            ++sp.gameSpeed;
        }
        sp.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    //这个按键控制游戏速度，只能减速，而且不能低于当前等级的最低速度
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        if ((sp.score < 10 && sp.gameSpeed > 0) || (sp.score < 20 && sp.gameSpeed > 1) || (sp.score < 30 && sp.gameSpeed > 4)) {
            --sp.gameSpeed;
        }
        sp.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    //把按钮属性的focusable取消就可以避免焦点在按钮上的问题了
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (!ctrl.pause) {
            switch (evt.getKeyCode()) {
                case 37:
                    if (ctrl.isOverstep(gp.x - 20, gp.y, gp.block1)) {
                        break;
                    }
                    ctrl.left();
                    break;
                case 39:
                    if (ctrl.isOverstep(gp.x + 20, gp.y, gp.block1)) {
                        break;
                    }
                    ctrl.right();
                    break;
                case 40:
                    if (ctrl.downIsOverstep(gp.x, gp.y + 20, gp.block1)) {
                        break;
                    }
                    ctrl.down();
                    break;
                case 38:
                    ctrl.turn();
                    break;
            }
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
