/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teris.cx;

import java.awt.Color;
import java.awt.Graphics;
import static java.lang.Math.random;
import java.util.Random;

/**
 *
 * @author Mactavish
 */
public class ScorePanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePanel
     */
    public int x;
    public int y;
    public int score;       //在sp显示得分
    public int gameSpeed;   //在sp显示并实际控制游戏速度

    public ScorePanel() {
        initComponents();
        x = 5;
        y = 20;
        score = 0;
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(Color.BLACK);
        g.drawString("得分      " + score, x, y);
        if (score < 10) {
            g.drawString("等级      1", x, y + 15);
        } else if (score < 20) {
            g.drawString("等级      2", x, y + 15);
        } else if (score < 30) {
            g.drawString("等级      3", x, y + 15);
        } else {
            g.drawString("等级      4", x, y + 15);
        }
        g.drawString("游戏速度    " + (gameSpeed+1), x, y + 30);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
